#-------------------------------
# General Site Settings(常规站点设置)
title: Blog
logo: tangerine.svg # You can add own logo.您可以添加自己的徽标。
description: 基本模板快速搭建的个人博客。| Zolan is modern minimal theme for Jekyll


#-------------------------------
# Author Settings 作者设置
author:
  name: 黄鹏举 
  image: author/001.jpg
  say-hello: 你好, 我是 <strong>黄鹏举</strong>
  # bio: Designs, talks, and writes about <strong>web</strong>, <strong>ethics</strong>, <strong>privacy</strong>, and dev. I share design tutorials, free resources and inspiration. Loves <a href="#">music</a> & riding his bicycle.
  bio: 我喜欢这句话：“无人问津也好，技不如人也罢，你都要试着安静下来，去做自己该做的事，而不是让内心的烦躁、焦虑，坏掉你本来就不多的热情和定力”。

#-------------------------------
# Contact links（联系人链接）
github: https://github.com/huangpengju # Add your Twitter handle
facebook: https://facebook.com/ # Add your Facebook handle
dribbble: https://dribbble.com/ # Add your Dribbble handle
instagram: https://instagram.com/ # Add your Instagram handle
pinterest: https://pinterest.com/ # Add your Pinterest handle


#-------------------------------
# Comment Section (Disqus)注释部分（Disqus）
disqus-identifier: mr-brown # add your shortname for Disqus Comment. For example mr-brown 添加Disqus Comment的简称。例如布朗先生


#-------------------------------
# Instagram Feed
instafeed: # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile: artemsheludko_ # Add instagram username


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
